### docker-compose.yml ###
version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - app-data:/app/packages/client-twitter/src/tweetcache
            - app-data:/app/db.sqlite
            - ./shared/.env:/app/.env
        env_file:
            - ./shared/.env
        environment:
            - NODE_ENV=production
            - PORT=3000
            - HOST=0.0.0.0
        ports:
            - "3000:3000"
            - "5173:5173"
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        command: sh -c "pnpm start & cd client && pnpm dev --host"

volumes:
    app-data:
        driver: local
