services:
    tee:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: eliza_staging
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - staging_tee:/app/packages/client-twitter/src/tweetcache
            - staging_tee:/app/db.sqlite
        env_file:
            - ./secrets/.env
        ports:
            - "3001:80"
        restart: always
        networks:
            - nova-network

volumes:
    staging_tee:

networks:
    nova-network:
        external: true
